---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs-test
annotations:
    gitlab.com/project-slug: StatusNeo/MDP-Docs
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:guest
